function [List] = CalculationDeclartion();

List = {'DayDiff'; ...
        'PercentageChange'; ...
        'PriceMean'; ...
        'VolumeDiff';
        'PriceMean_Denoised'; ...
        'ChangeMarker'; ...
        'TradeSignal'; ...
        'MovingAverage_30Day'
        'MovingAverage_15Day'
        'MovingAverage_5Day'};