function [functions] = StageDeclaration();

functions = {   ...
                'CreateDatabase'; ...
                'ImportInstruments'; ...
                'VerfiyYahoo'; ...
                'Download_Mat'; ...
                'DistributedComputing_Download_Mat'; ...
                'DateRange_Mat'; ...
                'NoOfSymbolsPerDay_Mat'; ...
                'DatabaseViewer_Mat'; ...
                'CalculateParameters_Mat'; ...
                'ValidDateRange';...
                'DayBestInvestments_Mat'; ...
                'HistoricalDayBestInvestments_Mat'; ...
                'Buy_Sell_Sequence'; ...
                'CalculateProfit'; ...
                'Descion';...
                'DescionPlus'; ...
                'CalculateStake'; ...
            };
                