%BB - BuyConf
DateNum = obj.DateNum;
DateNum = today;
Ticker = strrep(obj.LoadInvestedSymbols('InvestedSymbolList.txt'),'.L','');

FieldNames = {  'DL_Symbol', ...
                'DL_DateStr', ...
                'DL_YearEnd', ...
                'DL_Revenue', ...
                'DL_PreTax', ...
                'DL_EPS', ...
                'DL_PE', ...
                'DL_PEG', ...
                'DL_EPSGrth', ...
                'DL_Div', ...
                'DL_Yield'};
            
Folder = 'DL_InvestedSymbolForecasts';

% DateNum = obj.DateNum;
[DATASET] = obj.Quote(Ticker,FieldNames,DateNum);

%% Save Data
save([obj.InstallDir,'Results\',Folder,'\DataSet\',datestr(DateNum,1)],'DATASET');
% obj.DataSet2xls(DATASET,[obj.InstallDir,'Results\',Folder,'\xls\',datestr(DateNum,1),'.xls']);