%%
Folder = 'BrokerUpdates';
ThresholdDayOld = 30;

Symbols = obj.GetBBSymbolList;
try ...
    DATASET = obj.RecentEvents(Symbols,ThresholdDayOld); ...
catch ...
    disp('No events found'); ...
end
%%
% DATASET = obj.ColumnFiltering(DATASET,{ 'Symbol', ...
%                                         'DateStr', ...
%                                         'DaysOld', ...
%                                         'Event', ...
%                                         'MedianTargetDiff', ...
%                                         'OldTarget', ...
%                                         'NewTarget', ...
%                                         'Correction'});
                             
%
save([obj.InstallDir,'Results\',Folder,'\DataSet\',datestr(today,1)],'DATASET');
obj.DataSet2xls(DATASET,[obj.InstallDir,'Results\',Folder,'\xls\',datestr(now,1),'.xls']);
obj.DataSet2csv(DATASET,[obj.InstallDir,'Results\',Folder,'\ftbestpick.csv']);

%%
obj.SendFtp([obj.InstallDir,'\Results\',Folder,'\ftbestpick.csv'],['httpdocs/ft/',Folder],'wfoote.com','shares','cormorant');