function raw = download_wq(url)
    InstallDir = '';
    temp_filename = [InstallDir,'DL.iqy'];
    raw = ReadWebQuery(url,temp_filename);
end

function raw = ReadWebQuery(url,temp_filename)
    WriteWebQuery(url,temp_filename);
    [~,~,raw] = xlsread(temp_filename);
    delete(temp_filename)
end

function WriteWebQuery(string,temp_filename)
    fid = fopen(temp_filename, 'w');
    fprintf(fid, [ ...
        'WEB\n',...
        '1\n', ...
        string,'\n', ...
        '\n', ...
        'Selection=EntirePage\n', ...
        'Formatting=None\n', ...
        'PreFormattedTextToColumns=True\n', ...
        'ConsecutiveDelimitersAsOne=True\n', ...
        'SingleBlockTextImport=False\n', ...
        'DisableDateRecognition=False\n', ...
        'DisableRedirections=False']);
    fclose(fid);
end