function [symbol] = FailedLookUp(symbol)
% Old  -- > New

%TODO: OMXC20.CO not ^OMXC20.CO
symbols = { ...
        'ASXSP500.I ',    'AORD'; ...
        'FTSE100.I ',     'FTSE'; ...
        'FTSE250.I ',     'FTMC'; ...
        'NASCOMP.I ',     'IXIC'; ...
        'OMXC20.I ',      'OMXC20.CO'; ...
        'OMXS30.I ',      'OMXSPI'; ...
        'JCI.I ',         'JKSE'; ...
        'KOSPI.I ',       'KS11'; ...
        'DAX.I ',         'GDAXI'; ...
        'DAX100.I ',      'GDAXHI'; ...
        'SDAX.I ',        'SDAXI'; ...
        'CAC40.I ',       'FCHI'; ...
        'SP500.I ',       'GSPC';...
        
        'AEGN.AS',         'AGN.AS'; ...
        'AHLN.AS',         'AH.AS'; ...
        'AIRF.AS',         'AFA.AS'; ...
        'ASMI.AS',         'ASM.AS'; ...
        'AKZO.AS',         'AKZA.AS'; ...
        'BALNc.AS',        'BALNE.AS'; ...
        'BAMN.AS',         'BAMNB.AS'; ...
        'BOSN.AS',         'BOKA.AS'; ...
        'BTBN.AS',         'BATEN.AS'; ...
        'DJMC.AS',         'DJMC.AS'; ...
        'DSMN.AS',         'DSM.AS'; ...
        'ELSN.AS',         'REN.AS'; ...
        'FUR.AS',          'FUGRc.AS'; ...
        'HEIN.AS',         'HEIO.AS'; ...
        'HUDN.AS',         'HDG.AS'; ...
        'IAPD.AS',      'IAPD.AS'; ...
        'IEMM.AS',      'IEMM.AS'; ...
        'WEHA.AS',      'WHA.AS'; ...
        'VOPA.AS',      'VPK.AS'; ...
        'UNc.AS',       'UNA.AS'; ...
        'RBEN.AS',      'ROB.VI'; ...    
        'PHG.AS',       'PHIA.AS'; ...
        'OCEN.AS',      'OCE.AS'; ...
        'NUTR.AS',      'NUO.AS'; ...
                           };
    
[x] = size(symbols,1);
OldSymbols = symbols(:,1);
for i = 1:x
    n = find(strcmpi(OldSymbols{i},symbol));
    if not(isempty(n))
        symbol{n} = symbols{i,2};
    end
end