%% ['http://markets.ft.com/tearsheets/analysis.asp?s=',Symbol,'%3ALSE'];
obj.sURL = 'http://britishbulls.com/'; 
obj.eURL = '.asp';
obj.timeout = 2; %2 - only attempted once
Method = 'URL';

ProgramName = 'BritishBulls';
ResultName = 'ALL_STATUS';
MacroName = 'BritishBulls_ALLSTATUS';

Date = floor(now);
Date = obj.GetStoreDate(Date);

PageList = {'BasicMaterials'; ...
            'ConsumerGoods'; ...
            'ConsumerServices'; ...
            'Financials'; ...
            'HealthCare'; ...
            'Industrials'; ...
            'OilandGas'; ...
            'Technology'; ...
            'Telecommunications'; ...
            'Utilities'};
        
obj.SaveALL(Method,PageList,ProgramName,ResultName,Date,MacroName);